use crate::parser::ScalarDef;
use proc_macro2::TokenStream;
use quote::quote;

/// Map a GraphQL scalar name to its Rust type tokens.
pub fn scalar_to_rust_type(name: &str) -> Option<TokenStream> {
    match name {
        "DateTime" => Some(quote! { chrono::DateTime<chrono::Utc> }),
        "TimelessDate" => Some(quote! { chrono::NaiveDate }),
        "JSON" => Some(quote! { serde_json::Value }),
        "JSONObject" => Some(quote! { serde_json::Value }),
        "UUID" => Some(quote! { String }),
        "DateTimeOrDuration" | "TimelessDateOrDuration" | "Duration" => {
            Some(quote! { serde_json::Value })
        }
        _ => None,
    }
}

/// Generate scalar type alias definitions.
pub fn emit(scalars: &[ScalarDef]) -> TokenStream {
    let aliases: Vec<TokenStream> = scalars
        .iter()
        .filter_map(|s| {
            let rust_type = scalar_to_rust_type(&s.name)?;
            let name = quote::format_ident!("{}", s.name);
            Some(quote! {
                pub type #name = #rust_type;
            })
        })
        .collect();

    quote! {
        //! Custom scalar type aliases.
        //!
        //! Generated by lineark-codegen — do not edit.

        #(#aliases)*
    }
}

/// Map any GraphQL type name to its Rust type tokens.
/// Returns the Rust type for the base named type (no Option/Vec wrapping).
pub fn graphql_type_to_rust(name: &str) -> TokenStream {
    match name {
        "String" | "ID" | "UUID" => quote! { String },
        "Int" => quote! { i64 },
        "Float" => quote! { f64 },
        "Boolean" => quote! { bool },
        "DateTime" => quote! { chrono::DateTime<chrono::Utc> },
        "TimelessDate" => quote! { chrono::NaiveDate },
        "JSON" => quote! { serde_json::Value },
        "JSONObject" => quote! { serde_json::Value },
        // Custom Linear scalars that represent flexible types.
        "DateTimeOrDuration" | "TimelessDateOrDuration" | "Duration" => {
            quote! { serde_json::Value }
        }
        other => {
            // For enum types, use the type name directly (they're defined in enums.rs).
            // For anything else unknown, fall back to serde_json::Value.
            let ident = quote::format_ident!("{}", other);
            quote! { #ident }
        }
    }
}
