use crate::parser::EnumDef;
use heck::ToUpperCamelCase;
use proc_macro2::TokenStream;
use quote::quote;

pub fn emit(enums: &[EnumDef]) -> TokenStream {
    let enum_defs: Vec<TokenStream> = enums
        .iter()
        .filter(|e| !e.name.is_empty())
        .map(emit_enum)
        .collect();

    quote! {
        //! GraphQL enum types.
        //!
        //! Generated by lineark-codegen — do not edit.

        use serde::{Deserialize, Serialize};

        #(#enum_defs)*
    }
}

fn emit_enum(e: &EnumDef) -> TokenStream {
    let name = quote::format_ident!("{}", e.name);
    let variants: Vec<TokenStream> = e
        .values
        .iter()
        .filter(|v| !v.name.is_empty())
        .map(|v| {
            let original = &v.name;
            // Convert to PascalCase for Rust convention.
            let rust_name = to_variant_name(original);
            let variant_ident = quote::format_ident!("{}", rust_name);
            if rust_name == *original {
                quote! { #variant_ident, }
            } else {
                quote! {
                    #[serde(rename = #original)]
                    #variant_ident,
                }
            }
        })
        .collect();

    quote! {
        #[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
        pub enum #name {
            #(#variants)*
            /// Catch-all for unknown/new variants added by Linear.
            #[serde(other)]
            Unknown,
        }
    }
}

/// Convert a GraphQL enum value name to a valid Rust PascalCase variant name.
fn to_variant_name(name: &str) -> String {
    // If it's already PascalCase (e.g. "InProgress"), keep it.
    // If it's camelCase (e.g. "createdAt"), convert to PascalCase.
    // If it's SCREAMING_SNAKE (e.g. "IN_PROGRESS"), convert to PascalCase.
    // If it's a number or starts with a number, prefix with underscore.
    let pascal = name.to_upper_camel_case();
    if pascal.is_empty() {
        return format!("_{}", name);
    }
    // If first char is a digit, prefix.
    if pascal.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        format!("_{}", pascal)
    } else {
        pascal
    }
}
