use crate::emit_scalars::graphql_type_to_rust;
use crate::parser::{self, FieldDef, GqlType, InputDef, TypeKind};
use heck::ToSnakeCase;
use proc_macro2::TokenStream;
use quote::quote;
use std::collections::{HashMap, HashSet};

pub fn emit(inputs: &[InputDef], type_kind_map: &HashMap<String, TypeKind>) -> TokenStream {
    let defaultable = compute_defaultable_inputs(inputs, type_kind_map);

    let structs: Vec<TokenStream> = inputs
        .iter()
        .filter(|i| !i.name.is_empty())
        .map(|i| emit_input_struct(i, type_kind_map, &defaultable))
        .collect();

    quote! {
        //! GraphQL input types.
        //!
        //! Generated by lineark-codegen — do not edit.

        use serde::{Deserialize, Serialize};
        use super::enums::*;
        use crate::field_update::MaybeUndefined;

        #(#structs)*
    }
}

/// Compute which input structs can still derive `Default`.
///
/// Required (non-null) fields now emit as plain `T` instead of `Option<T>`, so
/// the struct only derives `Default` if every required field's Rust type also
/// has `Default`. Generated enums don't derive `Default`, and mutually recursive
/// input objects need a fixed-point pass to converge.
fn compute_defaultable_inputs(
    inputs: &[InputDef],
    type_kind_map: &HashMap<String, TypeKind>,
) -> HashSet<String> {
    let mut defaultable: HashSet<String> = inputs.iter().map(|i| i.name.clone()).collect();
    loop {
        let snapshot = defaultable.clone();
        defaultable.retain(|name| {
            let Some(input) = inputs.iter().find(|i| i.name == *name) else {
                return true;
            };
            input.fields.iter().all(|f| {
                // Nullable fields always have Default (MaybeUndefined::Undefined).
                if !matches!(f.ty, GqlType::NonNull(_)) {
                    return true;
                }
                type_has_default(&f.ty, type_kind_map, &snapshot)
            })
        });
        if defaultable.len() == snapshot.len() {
            break;
        }
    }
    defaultable
}

fn type_has_default(
    ty: &GqlType,
    type_kind_map: &HashMap<String, TypeKind>,
    defaultable_inputs: &HashSet<String>,
) -> bool {
    match ty {
        GqlType::NonNull(inner) => type_has_default(inner, type_kind_map, defaultable_inputs),
        GqlType::List(_) => true,
        GqlType::Named(name) => match type_kind_map.get(name.as_str()) {
            Some(TypeKind::Enum) => false,
            Some(TypeKind::InputObject) => defaultable_inputs.contains(name),
            _ => true,
        },
    }
}

fn emit_input_struct(
    input: &InputDef,
    type_kind_map: &HashMap<String, TypeKind>,
    defaultable: &HashSet<String>,
) -> TokenStream {
    let name = quote::format_ident!("{}", input.name);
    let doc = parser::doc_comment_tokens(&input.description);

    let fields: Vec<TokenStream> = input
        .fields
        .iter()
        .filter(|f| {
            if f.name.is_empty() {
                return false;
            }
            // Include all fields — union/interface/object types will be mapped to serde_json::Value.
            let base = f.ty.base_name();
            matches!(
                type_kind_map.get(base),
                Some(TypeKind::Scalar)
                    | Some(TypeKind::Enum)
                    | Some(TypeKind::InputObject)
                    | Some(TypeKind::Union)
                    | Some(TypeKind::Interface)
                    | Some(TypeKind::Object)
                    | None
            )
        })
        .map(|f| emit_field(f, type_kind_map))
        .collect();

    let derives = if defaultable.contains(&input.name) {
        quote! { #[derive(Debug, Clone, Default, Serialize, Deserialize)] }
    } else {
        quote! { #[derive(Debug, Clone, Serialize, Deserialize)] }
    };

    quote! {
        #doc
        #derives
        #[serde(rename_all = "camelCase")]
        pub struct #name {
            #(#fields)*
        }
    }
}

fn emit_field(f: &FieldDef, type_kind_map: &HashMap<String, TypeKind>) -> TokenStream {
    let field_name_str = f.name.to_snake_case();
    let original_name = &f.name;
    let safe_name = parser::safe_ident(&field_name_str);
    let field_ident = if safe_name.starts_with("r#") {
        let raw: TokenStream = safe_name.parse().unwrap();
        raw
    } else {
        let ident = quote::format_ident!("{}", safe_name);
        quote! { #ident }
    };

    let is_required = matches!(f.ty, GqlType::NonNull(_));
    let rust_type = resolve_input_type(&f.ty, type_kind_map);
    let fdoc = parser::doc_comment_tokens(&f.description);
    // If the snake_case name differs from the original camelCase, add serde rename.
    // We use rename_all on the struct level, so individual renames are only needed
    // if to_snake_case -> to_camelCase roundtrip doesn't match.
    let needs_rename = {
        let roundtrip = heck::AsLowerCamelCase(&field_name_str).to_string();
        roundtrip != *original_name
    };

    // Required fields are always serialized; nullable fields use MaybeUndefined's
    // skip predicate so `Undefined` omits the field from the JSON payload.
    let serde_attr = match (needs_rename, is_required) {
        (true, true) => quote! { #[serde(rename = #original_name)] },
        (false, true) => quote! {},
        (true, false) => quote! {
            #[serde(rename = #original_name, default, skip_serializing_if = "MaybeUndefined::is_undefined")]
        },
        (false, false) => quote! {
            #[serde(default, skip_serializing_if = "MaybeUndefined::is_undefined")]
        },
    };

    quote! {
        #fdoc
        #serde_attr
        pub #field_ident: #rust_type,
    }
}

/// Resolve a GraphQL input field type into its emitted Rust tokens.
///
/// Walks the type tree and applies nullability uniformly:
///
/// - At the **outermost** position, nullable wraps in `MaybeUndefined<T>` so
///   the consumer can distinguish "omit this field" from "send explicit null".
/// - **Inside a list**, nullable wraps in `Option<T>` — GraphQL list slots are
///   always materialized (no "omit this slot" wire form), so the three-state
///   distinction is meaningless one level in.
/// - Required positions emit plain `T` at any depth.
///
/// This handles every shape the GraphQL spec allows (`T`, `T!`, `[T!]!`,
/// `[T!]`, `[T]!`, `[T]`, and arbitrarily nested lists like `[[T!]!]!`)
/// without special-casing the schema.
fn resolve_input_type(ty: &GqlType, type_kind_map: &HashMap<String, TypeKind>) -> TokenStream {
    resolve(ty, type_kind_map, /* depth = */ 0)
}

fn resolve(ty: &GqlType, type_kind_map: &HashMap<String, TypeKind>, depth: usize) -> TokenStream {
    match ty {
        GqlType::NonNull(inner) => resolve_required(inner, type_kind_map, depth),
        other => {
            let inner = resolve_required(other, type_kind_map, depth);
            if depth == 0 {
                quote! { MaybeUndefined<#inner> }
            } else {
                quote! { Option<#inner> }
            }
        }
    }
}

fn resolve_required(
    ty: &GqlType,
    type_kind_map: &HashMap<String, TypeKind>,
    depth: usize,
) -> TokenStream {
    match ty {
        GqlType::Named(name) => {
            let kind = type_kind_map.get(name.as_str());
            if matches!(kind, Some(TypeKind::InputObject)) {
                let ident = quote::format_ident!("{}", name);
                // Self- and mutual-reference: input types reference other input
                // types in the same module.
                quote! { Box<#ident> }
            } else if matches!(
                kind,
                Some(TypeKind::Union) | Some(TypeKind::Interface) | Some(TypeKind::Object)
            ) {
                quote! { serde_json::Value }
            } else {
                graphql_type_to_rust(name)
            }
        }
        GqlType::NonNull(inner) => resolve_required(inner, type_kind_map, depth),
        GqlType::List(inner) => {
            let elem = resolve(inner, type_kind_map, depth + 1);
            quote! { Vec<#elem> }
        }
    }
}
